### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by notramo** [aarnt/octoxbps#8] opened 2020-05-17 10:38 UTC
I see a lot of activity on the `master` branch, but the latest release was in 2016 (and Void Linux still ships that version).

**Comment by mobinmob** [comment] 2020-05-17 12:00
I have a template for current  master as v. 0.2.3 : https://github.com/mobinmob/void-packages/tree/octoxbps for anyone who wants to test it. It is working fine for me :)

**Comment by AngryPhantom** [comment] 2020-05-20 20:17
@mobinmob 
I'm sorry, I'm still learning Void but how do I launch with admin rights? If I run it with sudo I get this [error](http://0x0.st/i9yd.png).

**Comment by AngryPhantom** [comment] 2020-05-20 20:28
@mobinmob 
Oops, my bad... I have version 0.2.2 for some reason. I've followed the xbps-src instructions:

$ git clone git://github.com/void-linux/void-packages.git
$ cd void-packages
$ ./xbps-src binary-bootstrap
$ ./xbps-src pkg octoxbps
And then:
# xbps-install --repository hostdir/binpkgs octoxbps

What am I doing wrong?
And sorry for my noob questions :(

**Comment by mobinmob** [comment] 2020-05-20 20:28
> @mobinmob
> I'm sorry, I'm still learning Void but how do I launch octoxbps with admin rights? If I run it with sudo I get this [error](http://0x0.st/i9yd.png).

You are not supposed to run octoxbps with admin rights. You run it as a user and it uses a su/sudo frontend for privilege elevation. That is why I suggested kdesu.

**Comment by AngryPhantom** [comment] 2020-05-20 20:29
I can't figure out why it pulled the previous version. See my comment above, please.

**Comment by mobinmob** [comment] 2020-05-20 20:31
@AngryPhantom : 2.2 is the latest released version. I have a template for the master in my repo/fork, not the official one.

**Comment by AngryPhantom** [comment] 2020-05-20 20:33
@mobinmob 
I see... And how can I use it? Simply git clone your repo?

**Comment by mobinmob** [comment] 2020-05-20 20:37
$ git clone https://github.com/mobinmob/void-packages
$ cd void-packages
$ ./xbps-src binary-bootstrap
$ git checkout octoxbps
$ ./xbps-src pkg octoxbps
And then:
$ xi octoxbps
`xi` is from the `xtools` package.

**Comment by AngryPhantom** [comment] 2020-05-20 21:25
Thanks, man! Now it works as expected (asking for pass when installing).

Offtopic: At first I didn't understand you and tried to install the very package with 'sudo xi octoxbps-0.2.3_2.x86_64.xbps' and got an error that this package was not found in repository pool. But then I searched Void docs and found out that it's meant to 'install a package into a repo', nothing more.
So, the question: is it really impossible in Void to install a package as it is (not from any local/online repo)?

**Comment by mobinmob** [comment] 2020-05-20 21:46
> Thanks, man! Now it works as expected (asking for pass when installing packages).
> 

;)
The octoxbps-sudo helper and the integrated terminal is really nice.

> Offtopic: At first I didn't understand you and tried to install the very package with 'sudo xi octoxbps-0.2.3_2.x86_64.xbps' and got an error that this package was not found in repository pool. But then I searched Void docs and found out that it's meant to 'install a package into a repo', nothing more.
> So, the question: is it really impossible in Void to install a package as it is (not from any local/online repo)? Assuming that I installed Void on another machine and have just this one package. No?

If you are asking for just the package directly (like `pacman -U package` or `gdebi package`) the answer is no. xbps needs repo metadata to work but it is extremely easy to create them with `xbps-rindex`. In fact, xbps-src creates repo metadata/repos with xbps-rindex per git branch. Your octoxbps package is in such a repo (hostdir/binpkgs/octoxbps).

**Comment by AngryPhantom** [comment] 2020-05-21 06:29
@mobinmob Thank you!

**Comment by AngryPhantom** [comment] 2020-05-21 06:37
@aarnt Is it possible to disable searching for packages while typing in octxbps? I mean, it's a bit heavy on CPU resources and when I type something it freezes for a second before I type another letter. Really annoying. Or just tell me what do I have to change in the code myself, please. I'd like to type some letters and then hit enter.
Honestly I don't understand why since the simplest script like this one:

`xbps-query -Rs "" | cut --delimiter " " --fields 1-2 | fzf --multi --exact --cycle --reverse --preview 'xbps-query -R {2}'`

is fast as a lightning actually. Is it really that Qt  is the culprit or what?..

Thank you.

**Comment by aarnt** [comment] 2020-05-21 11:00
Hi @AngryPhantom 
You can can uncheck  Search/Use Instant Search for that.
And you are right it is heavy on 12k packages. Maybe there is something that could be implemented to fix.

**Comment by AngryPhantom** [comment] 2020-05-21 15:12
@aarnt 

> Search/Use Instant Search

Omg, I went blind for a moment probably. Was looking for some Preferences and/or options for that.

Thank you and sorry for bothering. Awesome tool. Keep up the good work. Cheers!

**Comment by aarnt** [comment] 2020-05-21 15:29
@AngryPhantom 
:-)

**Comment by AngryPhantom** [comment] 2020-05-21 15:30
What I meant is that this script is fast as hell when you type anything:
`xbps-query -Rs "" | cut --delimiter " " --fields 1-2 | fzf --multi --exact --cycle --reverse --preview 'xbps-query -R {2}'`
The same package base. Strange.

**Comment by aarnt** [comment] 2020-05-21 17:08
@AngryPhantom 
But just out of curiosity. Are you using Search by description or search by name in OctoXBPS?
Moreover, what's your CPU?
Here I have a 11 year old CPU running VoidLinux in VM. Search by description is slow but search by name not exactly.

**Comment by AngryPhantom** [comment] 2020-05-21 17:28
@aarnt 
By name. When I type anything I can see that both CPU cores are like 50% in my conky monitor. And it 'freezes' after every letter which is not the case with the script.
CPU: AMD Athlon II X2 245

**Comment by notramo** [comment] 2020-05-21 19:50
@aarnt Don't forget the original topic of this issue.

**Comment by AngryPhantom** [comment] 2020-05-27 19:23
@mobinmob 
Sorry for bothering, I have another tiny question: what should I do if I want to edit the sources and then rebuild the package? I mean what should be done between (or instead of) these steps:
```
$ ./xbps-src binary-bootstrap
$ ./xbps-src pkg octoxbps
```
If I understand correctly the latter command just does everything and won't let me intrude and edit the sources before building, right?

**Comment by mobinmob** [comment] 2020-05-27 19:46
Just edit the template in srcpkgs/octoxbps/template
Please use my forked repo or even my email for further questions.

**Comment by AngryPhantom** [comment] 2020-05-27 19:50
@mobinmob 
Can't find your email...

**Comment by notramo** [comment] 2020-05-28 15:58
@aarnt Is there any reason that prevents releasing a new version?

**Comment by aarnt** [comment] 2020-05-28 16:37
@notramo 
No. Release of the 3 octo projects is really imminent.

**Comment by Kelvino9** [comment] 2020-06-25 08:58
Looking forward to the new release although OctoXBPS 0.2.2 does its job pretty well on my Xfce, KDE and Mate machines. Using OctoXBPS for daily system update notifications and it overall adds a lot of usability to a graphical user experience.

**Comment by aarnt** [comment] 2020-06-25 10:05
@Kelvino9 You're right. Xbps is a very competent pkgman but the fact It ships with many executables can be daunting to new users.

**Comment by Kelvino9** [comment] 2020-06-25 10:29
That's true. I had to fiddle around for a while to make OctoXBPS work as intended on Xfce and Mate. On KDE it almost or immediately worked out of the box. Can't remember anymore.

 The system update notification is awesome although I couldn't figure out how to avoid entering a password for a repo sync.

**Comment by aarnt** [comment] 2020-06-25 13:17
@Kelvino9 
Don't worry, those issues will be fixed in 0.3.0.
No password for notifier syncing and no kde/gnome/lxqt dependencies to get root privileges anymore.

**Comment by Kelvino9** [comment] 2020-06-25 13:28
Thanks @aarnt! That's amazing news.

**Comment by aarnt** [comment] 2020-07-19 16:27
v0.3.0 released!

**Closed by aarnt** 2020-07-19 16:27 UTC

**Comment by testbird** [comment] 2021-04-23 21:59
> You can can uncheck Search/Use Instant Search for that.
> And you are right it is heavy on 12k packages. Maybe there is something that could be implemented to fix.

Unnecessary load might be avoidable by only starting a search after getting the second character, and setting a timeout after each typed character to 1000-<number-of-chars*200)ms.
